
dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.206.130:2181
  protocol:
    port: 28800
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pro_1910
    username: root
    password: 123
