dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 192.168.206.130:2181
  protocol:
    port: 28801
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///pro_1910
    username: root
    password: 123
  data:
    solr:
      host: http://192.168.206.130:8080/solr
  rabbitmq:
    host: 192.168.206.130
    port: 5672
    username: czt
    password: 123
    virtual-host: /czt