
dubbo:
  application:
    name: backgroud
  registry:
    protocol: zookeeper
    address: 192.168.206.130:2181
server:
  port: 9090
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.206.130:22122
image:
  server: http://192.168.206.130/
spring:
  rabbitmq:
    host: 192.168.206.130
    port: 5672
    username: czt
    password: 123
    virtual-host: /czt
